export const questionTest = {
  strategic: [
    {
      category_en: "Organizational Preparedness",
      category_id: "Kesiapan Organisasi",
      acronym: "OP",
      icon: "/img/rra-icon/icon-1.png",
      detail: [
        {
          code: "A.1.1",
          question_en: "Does the organization have a cybersecurity policy that includes ransomware response?",
          question_id: "Apakah organisasi memiliki kebijakan keamanan siber yang mencakup respons ransomware?",
          hint_en: "The cybersecurity policy should include prevention measures (such as system updates and employee training), detection (such as network monitoring), response (such as isolating infected systems), and recovery (such as data restoration from backups). Ensure the policy aligns with NIST SP 800-53 (specific security controls for ransomware) or ISO/IEC 27001 (information security management).",
          hint_id: "Kebijakan keamanan siber harus mencakup langkah-langkah pencegahan (seperti pembaruan sistem dan pelatihan karyawan), deteksi (seperti pemantauan jaringan), respons (seperti isolasi sistem yang terinfeksi), dan pemulihan (seperti pemulihan data dari backup). Pastikan kebijakan ini sesuai dengan standar NIST SP 800-53 (kontrol keamanan khusus untuk ransomware) atau ISO/IEC 27001 (manajemen keamanan informasi).",
          icon: "bi bi-shield-lock-fill",
        },
        {
          code: "A.1.2",
          question_en: "Is there strategic planning for cyber risks involving cross-functional teams (IT, legal, PR, management)?",
          question_id: "Apakah terdapat perencanaan strategis untuk risiko siber yang melibatkan tim lintas fungsi (IT, legal, PR, manajemen)?",
          hint_en: "The strategic plan should involve various departments to ensure effective coordination during a ransomware attack. Include IT for technical aspects, legal for legal implications, PR for public communication, and management for strategic decisions. Use the NIST Cybersecurity Framework (CSF) to integrate these functions.",
          hint_id: "Rencana strategis harus melibatkan berbagai departemen untuk memastikan koordinasi yang efektif selama serangan ransomware. Libatkan IT untuk aspek teknis, legal untuk implikasi hukum, PR untuk komunikasi publik, manajemen untuk keputusan strategis. Gunakan kerangka kerja NIST Cybersecurity Framework (CSF) untuk mengintegrasikan berbagai fungsi ini.",
          icon: "bi bi-people",
        },
        {
          code: "A.1.3",
          question_en: "Have all digital assets (software, hardware, and data) been identified, classified, and prioritized for protection?",
          question_id: "Apakah semua aset digital (perangkat lunak, perangkat keras, dan data) telah diidentifikasi, diklasifikasikan, dan diprioritaskan untuk perlindungan?",
          hint_en: "Conduct an inventory of digital and physical assets, then prioritize them based on business impact in case of an attack. Use the NIST SP 800-30 approach for asset risk assessment and data classification based on sensitivity (e.g., personal data, financial data, and operational data).",
          hint_id: "Lakukan inventarisasi aset digital dan fisik, lalu prioritaskan berdasarkan dampak bisnis jika terjadi serangan. Gunakan pendekatan NIST SP 800-30 untuk penilaian risiko aset dan klasifikasi data berdasarkan sensitivitas (misalnya, data pribadi, data finansial, dan data operasional).",
          icon: "bi bi-archive-fill",
        },
      ],
      overallScore: 90,
    },
    {
      category_en: "Risk Management",
      category_id: "Manajemen Risiko",
      acronym: "RM",
      icon: "/img/rra-icon/icon-2.png",
      detail: [
        {
          code: "A.2.1",
          question_en: "Has ransomware risk been included in the organization's risk map with clear likelihood and impact assessments?",
          question_id: "Apakah risiko ransomware telah dimasukkan ke dalam peta risiko organisasi dengan penilaian kemungkinan dan dampak yang jelas?",
          hint_en: "Ensure the risk map includes the likelihood and impact of ransomware attacks. Use ISO 27005 or NIST IRAM (Integrated Risk Assessment Methodology) to assess risks. Consider factors such as system vulnerabilities, relevant threats, and financial or reputational impact.",
          hint_id: "Pastikan peta risiko mencakup kemungkinan dan dampak serangan ransomware. Gunakan metodologi ISO 27005 atau NIST IRAM (Integrated Risk Assessment Methodology) untuk menilai risiko. Pertimbangkan faktor seperti kerentanan sistem, ancaman yang relevan, dan dampak finansial atau reputasi.",
          icon: "bi bi-map-fill",
        },
        {
          code: "A.2.2",
          question_en: "Is there a mechanism to assess risks from third parties (vendors, cloud service providers, or MSPs) that have access to the organization's systems or data?",
          question_id: "Apakah ada mekanisme untuk menilai risiko dari pihak ketiga (vendor, penyedia layanan cloud, atau MSP) yang memiliki akses ke sistem atau data organisasi?",
          hint_en: "Conduct risk assessments on vendors and business partners with access to your systems or data. Ensure contracts include cybersecurity and incident response clauses, in line with ISO 27001 or NIST SP 800-161 (supply chain risk management). Use tools like SIG (Standardized Information Gathering) to assess vendor security.",
          hint_id: "Lakukan penilaian risiko terhadap vendor dan mitra bisnis yang memiliki akses ke sistem atau data Anda. Pastikan kontrak mencakup klausul keamanan siber dan respons insiden, sesuai dengan ISO 27001 atau NIST SP 800-161 (manajemen risiko rantai pasokan). Gunakan alat seperti SIG (Standardized Information Gathering) untuk menilai keamanan vendor.",
          icon: "bi bi-diagram-2-fill",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Insurance Coverage",
      category_id: "Cakupan Asuransi",
      acronym: "IC",
      icon: "/img/rra-icon/icon-3.png",
      detail: [
        {
          code: "A.3.1",
          question_en: "Does the organization have a cyber insurance policy that covers ransomware and extortion?",
          question_id: "Apakah organisasi memiliki polis asuransi siber yang mencakup ransomware dan extortion?",
          hint_en: "Ensure the insurance policy covers recovery costs, ransom payments (if necessary), and business losses due to ransomware attacks. Discuss with the insurance broker to understand coverage and exclusions, ensuring alignment with industry standards like ISO 27032 (cybersecurity guidelines).",
          hint_id: "Pastikan polis asuransi mencakup biaya pemulihan, pembayaran tebusan (jika diperlukan), dan kerugian bisnis akibat serangan ransomware. Diskusikan dengan broker asuransi untuk memahami cakupan dan pengecualian, serta pastikan sesuai dengan standar industri seperti ISO 27032 (panduan keamanan siber).",
          icon: "bi bi-file-earmark-lock-fill",
        },
      ],
      overallScore: 30,
    },
    {
      category_en: "Training and Awareness",
      category_id: "Pelatihan dan Kesadaran",
      acronym: "TA",
      icon: "/img/rra-icon/icon-4.png",
      detail: [
        {
          code: "A.4.1",
          question_en: "Do employees receive regular cybersecurity training, including phishing simulations and incident response training?",
          question_id: "Apakah karyawan menerima pelatihan keamanan siber secara berkala, termasuk simulasi phishing dan pelatihan respons insiden?",
          hint_en: "Conduct regular training to increase employee awareness of cyber threats like phishing, which is often an entry point for ransomware attacks. Use NIST SP 800-50 (Building an Information Technology Security Awareness and Training Program) for a cybersecurity training program.",
          hint_id: "Lakukan pelatihan rutin untuk meningkatkan kesadaran karyawan tentang ancaman siber seperti phishing, yang sering menjadi pintu masuk serangan ransomware. Gunakan panduan NIST SP 800-50 (Building an Information Technology Security Awareness and Training Program) untuk program pelatihan keamanan siber.",
          icon: "bi bi-person-video",
        },
        {
          code: "A.4.2",
          question_en: "Does management understand the strategic impact of ransomware on business continuity?",
          question_id: "Apakah manajemen memahami dampak strategis ransomware terhadap keberlanjutan bisnis?",
          hint_en: "Management should understand that ransomware can disrupt operations, damage reputation, and cause significant financial losses. Prepare a Business Continuity Plan (BCP) based on ISO 22301 (business continuity management).",
          hint_id: "Manajemen harus memahami bahwa ransomware dapat mengganggu operasional, merusak reputasi, dan menyebabkan kerugian finansial yang signifikan. Siapkan rencana bisnis berkelanjutan (BCP) berdasarkan ISO 22301 (manajemen kelangsungan bisnis).",
          icon: "bi bi-bar-chart-fill",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Incident Response Plan",
      category_id: "Rencana Respons Insiden",
      acronym: "IRP",
      icon: "/img/rra-icon/icon-5.png",
      detail: [
        {
          code: "A.5.1",
          question_en: "Does the organization have a tested ransomware incident response plan?",
          question_id: "Apakah organisasi memiliki rencana respons insiden ransomware yang telah diuji coba?",
          hint_en: "The incident response plan should include detection steps (such as SIEM monitoring), isolation (such as disconnecting infected systems from the network), recovery (such as restoring data from backups), and communication (such as informing customers and regulators). Conduct regular drills (tabletop exercises) based on NIST SP 800-61 (Computer Security Incident Handling Guide) or ISO 27035 (information security incident management).",
          hint_id: "Rencana respons insiden harus mencakup langkah-langkah deteksi (seperti pemantauan SIEM), isolasi (seperti memutus sistem yang terinfeksi dari jaringan), pemulihan (seperti pemulihan data dari backup), dan komunikasi (seperti menginformasikan pelanggan dan regulator). Lakukan latihan rutin (tabletop exercise) berdasarkan NIST SP 800-61 (Computer Security Incident Handling Guide) atau ISO 27035 (manajemen insiden keamanan informasi).",
          icon: "bi bi-exclamation-octagon-fill",
        },
        {
          code: "A.5.2",
          question_en: "Is there a procedure to decide whether to pay the ransom or not?",
          question_id: "Apakah ada prosedur untuk memutuskan apakah akan membayar tebusan atau tidak?",
          hint_en: "Create a procedure involving management, legal, and finance teams to evaluate the decision to pay the ransom. Consider factors such as backup availability, data leakage risks, and legal implications (e.g., compliance with OFAC or GDPR).",
          hint_id: "Buat prosedur yang melibatkan tim manajemen, legal, dan keuangan untuk mengevaluasi keputusan membayar tebusan. Pertimbangkan faktor seperti ketersediaan backup, risiko kebocoran data, dan implikasi hukum (misalnya, kepatuhan terhadap OFAC atau GDPR).",
          icon: "bi bi-cash",
        },
        {
          code: "A.5.3",
          question_en: "Has the crisis management team been trained to handle pressure during an attack?",
          question_id: "Apakah tim manajemen krisis telah dilatih untuk menangani tekanan selama serangan?",
          hint_en: "Train the crisis management team to remain calm and make quick decisions under pressure. Use simulation scenarios based on ISO 22301 for crisis management training.",
          hint_id: "Latih tim manajemen krisis untuk tetap tenang dan mengambil keputusan cepat di bawah tekanan. Gunakan skenario simulasi berdasarkan ISO 22301 untuk pelatihan manajemen krisis.",
          icon: "bi bi-person-lines-fill",
        },
      ],
      overallScore: 90,
    },
    {
      category_en: "Legal and Compliance",
      category_id: "Hukum dan Kepatuhan",
      acronym: "LC",
      icon: "/img/rra-icon/icon-6.png",
      detail: [
        {
          code: "A.6.1",
          question_en: "Does the organization understand incident reporting requirements under applicable regulations?",
          question_id: "Apakah organisasi memahami persyaratan pelaporan insiden berdasarkan regulasi yang berlaku?",
          hint_en: "Understand regulations such as GDPR (General Data Protection Regulation), PDP Law (Personal Data Protection), or CCPA (California Consumer Privacy Act) that mandate cyber incident reporting. Ensure the reporting process complies with deadlines and requirements.",
          hint_id: "Pelajari regulasi seperti GDPR (General Data Protection Regulation), UU PDP (Perlindungan Data Pribadi), atau CCPA (California Consumer Privacy Act) yang mewajibkan pelaporan insiden siber. Pastikan proses pelaporan sesuai dengan batas waktu dan persyaratan yang ditetapkan.",
          icon: "bi bi-file-text-fill",
        },
        {
          code: "A.6.2",
          question_en: "Is there a policy to collaborate with law enforcement or regulators during an incident?",
          question_id: "Apakah ada kebijakan untuk bekerja sama dengan penegak hukum atau regulator saat terjadi insiden?",
          hint_en: "Create a protocol to involve law enforcement or regulators in incident investigations. Ensure the legal team understands the organization's rights and obligations during this process.",
          hint_id: "Buat protokol untuk melibatkan penegak hukum atau regulator dalam investigasi insiden. Pastikan tim legal memahami hak dan kewajiban organisasi selama proses ini.",
          icon: "bi bi-shield-check",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Establish Negotiation Protocols",
      category_id: "Menetapkan Protokol Negosiasi",
      acronym: "ENP",
      icon: "/img/rra-icon/icon-7.png",
      detail: [
        {
          code: "A.7.1",
          question_en: "Is there a standard procedure for negotiating with ransomware actors?",
          question_id: "Apakah ada prosedur standar untuk negosiasi dengan pelaku ransomware?",
          hint_en: "Prepare a script or negotiation guide that includes key questions, time limits, and escalation steps. Involve third-party negotiators if necessary.",
          hint_id: "Siapkan skrip atau panduan negosiasi yang mencakup pertanyaan kunci, batasan waktu, dan langkah-langkah eskalasi. Libatkan ahli negosiasi pihak ketiga jika diperlukan.",
          icon: "bi bi-chat-right-dots-fill",
        },
        {
          code: "A.7.2",
          question_en: "Has the team been trained to understand psychological pressure during negotiations?",
          question_id: "Apakah tim telah dilatih untuk memahami tekanan psikologis dalam negosiasi?",
          hint_en: "Train the team to handle psychological pressure, such as threats of data leaks or tight deadlines. Use simulations to train negotiation skills.",
          hint_id: "Latih tim untuk menghadapi tekanan psikologis seperti ancaman kebocoran data atau tenggat waktu yang ketat. Gunakan simulasi untuk melatih keterampilan negosiasi.",
          icon: "bi bi-emoji-dizzy",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Identify Negotiation Team",
      category_id: "Mengidentifikasi Tim Negosiasi",
      acronym: "INT",
      icon: "/img/rra-icon/icon-8.png",
      detail: [
        {
          code: "A.8.1",
          question_en: "Is there a dedicated team to handle negotiations, including legal, technical, and third-party experts (e.g., ransomware consultants)?",
          question_id: "Apakah ada tim khusus untuk menangani negosiasi, termasuk ahli hukum, teknis, dan pihak ketiga (misalnya, konsultan ransomware)?",
          hint_en: "Form a team consisting of legal experts, IT, and professional negotiators. Ensure they have quick access to necessary information during negotiations.",
          hint_id: "Bentuk tim yang terdiri dari ahli hukum, IT, dan negosiator profesional. Pastikan mereka memiliki akses cepat ke informasi yang diperlukan selama negosiasi.",
          icon: "bi bi-people-fill",
        },
      ],
      overallScore: 30,
    },
    {
      category_en: "Budget and Payment Strategy",
      category_id: "Anggaran dan Strategi Pembayaran",
      acronym: "BPS",
      icon: "/img/rra-icon/icon-9.png",
      detail: [
        {
          code: "A.9.1",
          question_en: "Is there a budget prepared to pay a ransom if necessary (including through insurance)?",
          question_id: "Apakah ada anggaran yang disiapkan untuk membayar tebusan jika diperlukan (termasuk melalui asuransi)?",
          hint_en: "Prepare an emergency fund or ensure the insurance policy covers ransom payments. Discuss with the finance team to ensure fund availability.",
          hint_id: "Siapkan dana darurat atau pastikan polis asuransi mencakup pembayaran tebusan. Diskusikan dengan tim keuangan untuk memastikan ketersediaan dana.",
          icon: "bi bi-wallet-fill",
        },
        {
          code: "A.9.2",
          question_en: "Is there a policy governing the decision to pay or not pay a ransom?",
          question_id: "Apakah ada kebijakan yang mengatur keputusan membayar atau tidak membayar tebusan?",
          hint_en: "Create a clear policy on when and how ransom payment decisions are made. Consider factors such as backup availability, data leakage risks, and legal implications (e.g., compliance with OFAC).",
          hint_id: "Buat kebijakan yang jelas tentang kapan dan bagaimana keputusan membayar tebusan diambil. Pertimbangkan faktor seperti ketersediaan backup, risiko kebocoran data, dan implikasi hukum (misalnya, kepatuhan terhadap OFAC).",
          icon: "bi bi-card-checklist",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Secure Communication Channels",
      category_id: "Saluran Komunikasi Aman",
      acronym: "SCC",
      icon: "/img/rra-icon/icon-12.png",
      detail: [
        {
          code: "A.10.1",
          question_en: "Does the organization have access to secure communication channels to communicate with ransomware actors?",
          question_id: "Apakah organisasi memiliki akses ke saluran komunikasi yang aman untuk berbicara dengan pelaku ransomware?",
          hint_en: "Use encrypted communication tools like Tor or specialized platforms to interact with ransomware actors. Avoid using internal communication channels that may be compromised.",
          hint_id: "Gunakan alat komunikasi terenkripsi seperti Tor atau platform khusus untuk berinteraksi dengan pelaku ransomware. Hindari menggunakan saluran komunikasi internal yang dapat dikompromikan.",
          icon: "bi bi-shield-lock",
        },
      ],
      overallScore: 30,
    },
  ],
  tactic: [
    {
      category_en: "Access Controls",
      category_id: "Kontrol Akses",
      acronym: "AC",
      icon: "/img/rra-icon/icon-11.png",
      detail: [
        {
          code: "B.1.1",
          question_en: "Is multi-factor authentication (MFA) implemented on all accounts with access to sensitive systems or data?",
          question_id: "Apakah autentikasi multifaktor (MFA) diterapkan pada semua akun yang memiliki akses ke sistem atau data sensitif?",
          hint_en: "MFA should be implemented on all accounts with access to sensitive systems or data. Use NIST SP 800-63B (Digital Identity Guidelines) for effective MFA implementation guidance.",
          hint_id: "MFA harus diterapkan pada semua akun yang memiliki akses ke sistem atau data sensitif. Gunakan standar NIST SP 800-63B (Digital Identity Guidelines) untuk panduan implementasi MFA yang efektif.",
          icon: "bi bi-lock-fill",
        },
        {
          code: "B.1.2",
          question_en: "Does the system have a strong password policy, including a minimum length of 12 characters, complexity, and regular changes every 90 days?",
          question_id: "Apakah sistem memiliki kebijakan kata sandi yang kuat, termasuk panjang minimal 12 karakter, kompleksitas, dan penggantian rutin setiap 90 hari?",
          hint_en: "The password policy should include a minimum length of 12 characters, complexity (uppercase, lowercase, numbers, and symbols), and a change frequency of every 90 days. Use NIST SP 800-63B recommendations for a strong password policy.",
          hint_id: "Kebijakan kata sandi harus mencakup panjang minimal 12 karakter, kompleksitas (huruf besar, huruf kecil, angka, dan simbol), dan frekuensi penggantian setiap 90 hari. Gunakan rekomendasi NIST SP 800-63B untuk kebijakan kata sandi yang kuat.",
          icon: "bi bi-key-fill",
        },
        {
          code: "B.1.3",
          question_en: "Is user access restricted based on the principle of least privilege?",
          question_id: "Apakah akses pengguna dibatasi berdasarkan prinsip least privilege?",
          hint_en: "Ensure users only have access to systems and data necessary for their roles. This principle aligns with ISO 27001 and NIST SP 800-53 (access control security).",
          hint_id: "Pastikan pengguna hanya memiliki akses ke sistem dan data yang diperlukan untuk pekerjaan mereka. Prinsip ini sesuai dengan ISO 27001 dan NIST SP 800-53 (kontrol keamanan akses).",
          icon: "bi bi-person-lock",
        },
      ],
      overallScore: 90,
    },
    {
      category_en: "Network Segmentation",
      category_id: "Segmentasi Jaringan",
      acronym: "NS",
      icon: "/img/rra-icon/icon-12.png",
      detail: [
        {
          code: "B.2.1",
          question_en: "Has the organization's network been segmented to limit the spread of malware, including network isolation for sensitive data?",
          question_id: "Apakah jaringan organisasi telah disegmentasi untuk membatasi penyebaran malware, termasuk isolasi jaringan untuk data sensitif?",
          hint_en: "Network segmentation helps limit the spread of ransomware. Use NIST SP 800-82 (Guide to Industrial Control Systems Security) for effective segmentation implementation.",
          hint_id: "Segmentasi jaringan membantu membatasi penyebaran ransomware. Gunakan panduan NIST SP 800-82 (Guide to Industrial Control Systems Security) untuk implementasi segmentasi yang efektif.",
          icon: "bi bi-diagram-3-fill",
        },
        {
          code: "B.2.2",
          question_en: "Is access to sensitive data isolated from other parts of the network with strict access controls?",
          question_id: "Apakah akses ke data sensitif diisolasi dari bagian lain jaringan dengan kontrol akses yang ketat?",
          hint_en: "Sensitive data should be placed in an isolated network with strict access controls. Use zero trust principles and micro-segmentation to enhance security.",
          hint_id: "Data sensitif harus ditempatkan di jaringan terisolasi dengan kontrol akses yang ketat. Gunakan prinsip zero trust dan micro-segmentation untuk meningkatkan keamanan.",
          icon: "bi bi-shield-fill-x",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Backup",
      category_id: "Cadangan",
      acronym: "BU",
      icon: "/img/rra-icon/icon-13.png",
      detail: [
        {
          code: "B.3.1",
          question_en: "Does the organization have encrypted backups that are not connected to the main network (offline/immutable)?",
          question_id: "Apakah organisasi memiliki backup data yang terenkripsi dan tidak terhubung ke jaringan utama (offline/immutable)?",
          hint_en: "Backups should be stored in an encrypted format and not connected to the main network (offline or immutable). Use NIST SP 800-171 (Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations) for secure backup management.",
          hint_id: "Backup harus disimpan dalam format terenkripsi dan tidak terhubung ke jaringan utama (offline atau immutable). Gunakan standar NIST SP 800-171 (Protecting Controlled Unclassified Information in Nonfederal Systems and Organizations) untuk manajemen backup yang aman.",
          icon: "bi bi-hdd-fill",
        },
        {
          code: "B.3.2",
          question_en: "Are backups tested regularly to ensure validity and recovery speed?",
          question_id: "Apakah backup diuji secara berkala untuk memastikan validitas dan kecepatan pemulihan?",
          hint_en: "Conduct regular backup recovery tests to ensure data can be restored quickly and accurately. Use ISO 27001 guidelines for backup management.",
          hint_id: "Lakukan uji pemulihan backup secara berkala untuk memastikan data dapat dipulihkan dengan cepat dan akurat. Gunakan panduan ISO 27001 untuk manajemen backup.",
          icon: "bi bi-check-circle-fill",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Endpoint Protection",
      category_id: "Perlindungan Endpoint",
      acronym: "EP",
      icon: "/img/rra-icon/icon-14.png",
      detail: [
        {
          code: "B.4.1",
          question_en: "Are endpoints equipped with endpoint detection and response (EDR/XDR) software?",
          question_id: "Apakah endpoint dilengkapi dengan perangkat lunak deteksi dan respons endpoint (EDR/XDR)?",
          hint_en: "Use EDR/XDR solutions to detect and respond to threats at the endpoint level. These solutions should align with NIST SP 800-37 (Risk Management Framework) and MITRE ATT&CK Framework.",
          hint_id: "Gunakan solusi EDR/XDR untuk mendeteksi dan merespons ancaman di tingkat endpoint. Solusi ini harus sesuai dengan standar NIST SP 800-37 (Risk Management Framework) dan MITRE ATT&CK Framework.",
          icon: "bi bi-display",
        },
        {
          code: "B.4.2",
          question_en: "Are all devices updated with the latest software and security patches?",
          question_id: "Apakah semua perangkat memiliki pembaruan perangkat lunak dan patch terbaru?",
          hint_en: "Ensure all devices are updated with the latest security patches. Use a patch management process aligned with NIST SP 800-40 (Creating a Patch and Vulnerability Management Program).",
          hint_id: "Pastikan semua perangkat diperbarui dengan patch keamanan terbaru. Gunakan proses manajemen patch yang sesuai dengan NIST SP 800-40 (Creating a Patch and Vulnerability Management Program).",
          icon: "bi bi-arrow-repeat",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Threat Detection and Monitoring",
      category_id: "Deteksi dan Pemantauan Ancaman",
      acronym: "TDM",
      icon: "/img/rra-icon/icon-15.png",
      detail: [
        {
          code: "B.5.1",
          question_en: "Does the organization use SIEM or a similar monitoring system to detect suspicious activity?",
          question_id: "Apakah organisasi menggunakan SIEM atau sistem pemantauan serupa untuk mendeteksi aktivitas mencurigakan?",
          hint_en: "Implement SIEM to monitor and analyze network activity. Use NIST SP 800-137 (Information Security Continuous Monitoring) for SIEM implementation guidance.",
          hint_id: "Implementasikan SIEM untuk memantau dan menganalisis aktivitas jaringan. Gunakan standar NIST SP 800-137 (Information Security Continuous Monitoring) untuk panduan implementasi SIEM.",
          icon: "bi bi-binoculars-fill",
        },
        {
          code: "B.5.2",
          question_en: "Are Indicators of Compromise (IoCs) updated regularly?",
          question_id: "Apakah Indicators of Compromise (IoCs) diperbarui secara berkala?",
          hint_en: "Update IoCs regularly based on the latest threats. Use sources like MITRE ATT&CK or CISA (Cybersecurity and Infrastructure Security Agency) to obtain the latest IoCs.",
          hint_id: "Perbarui IoCs secara berkala berdasarkan ancaman terbaru. Gunakan sumber seperti MITRE ATT&CK atau CISA (Cybersecurity and Infrastructure Security Agency) untuk mendapatkan IoCs terkini.",
          icon: "bi bi-arrow-clockwise",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Phishing Protection",
      category_id: "Perlindungan Phishing",
      acronym: "PP",
      icon: "/img/rra-icon/icon-16.png",
      detail: [
        {
          code: "B.6.1",
          question_en: "Does the organization have email filters to detect and block phishing emails?",
          question_id: "Apakah organisasi memiliki filter email untuk mendeteksi dan memblokir email phishing?",
          hint_en: "Use AI or machine learning-based email filters to detect and block phishing emails. These solutions should align with NIST SP 800-45 (Guidelines on Electronic Mail Security).",
          hint_id: "Gunakan filter email berbasis AI atau machine learning untuk mendeteksi dan memblokir email phishing. Solusi ini harus sesuai dengan standar NIST SP 800-45 (Guidelines on Electronic Mail Security).",
          icon: "bi bi-envelope-check-fill",
        },
        {
          code: "B.6.2",
          question_en: "Are regular phishing simulation trainings conducted?",
          question_id: "Apakah ada pelatihan simulasi phishing secara rutin?",
          hint_en: "Conduct regular phishing simulation training to increase employee awareness. Use NIST SP 800-16 (Information Technology Security Training Requirements) for a cybersecurity training program.",
          hint_id: "Lakukan pelatihan simulasi phishing secara berkala untuk meningkatkan kesadaran karyawan. Gunakan panduan NIST SP 800-16 (Information Technology Security Training Requirements) untuk program pelatihan keamanan siber.",
          icon: "bi bi-person-x-fill",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Incident Containment",
      category_id: "Penahanan Insiden",
      acronym: "IC",
      icon: "/img/rra-icon/icon-17.png",
      detail: [
        {
          code: "B.7.1",
          question_en: "Are procedures in place to stop the spread of malware, such as isolating infected systems?",
          question_id: "Apakah prosedur untuk menghentikan penyebaran malware telah disiapkan, seperti isolasi sistem yang terinfeksi?",
          hint_en: "Prepare procedures to isolate infected systems and limit the spread of ransomware. Use NIST SP 800-61 (Computer Security Incident Handling Guide) for incident response.",
          hint_id: "Siapkan prosedur untuk mengisolasi sistem yang terinfeksi dan membatasi penyebaran ransomware. Gunakan panduan NIST SP 800-61 (Computer Security Incident Handling Guide) untuk respons insiden.",
          icon: "bi bi-box-seam-fill",
        },
        {
          code: "B.7.2",
          question_en: "Does the organization have a policy to disconnect from the Internet during a ransomware incident?",
          question_id: "Apakah organisasi memiliki kebijakan untuk memutus koneksi ke Internet selama insiden ransomware?",
          hint_en: "Create a policy to disconnect from the Internet if necessary during a ransomware attack. This can help prevent data exfiltration.",
          hint_id: "Buat kebijakan untuk memutus koneksi Internet jika diperlukan selama serangan ransomware. Ini dapat membantu mencegah eksfiltrasi data.",
          icon: "bi bi-wifi-off",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Recovery Protocols",
      category_id: "Protokol Pemulihan",
      acronym: "RP",
      icon: "/img/rra-icon/icon-18.png",
      detail: [
        {
          code: "B.8.1",
          question_en: "Are there procedures to recover data from backups without disrupting other critical operations?",
          question_id: "Apakah ada prosedur untuk memulihkan data dari backup tanpa mengganggu operasi kritis lainnya?",
          hint_en: "Prepare structured and tested data recovery procedures. Use ISO 22301 (Business Continuity Management) for disaster recovery management.",
          hint_id: "Siapkan prosedur pemulihan data yang terstruktur dan teruji. Gunakan standar ISO 22301 (Business Continuity Management) untuk manajemen pemulihan bencana.",
          icon: "bi bi-arrow-counterclockwise",
        },
        {
          code: "B.8.2",
          question_en: "Has the organization identified essential services that need to be recovered first (recovery priorities)?",
          question_id: "Apakah organisasi telah mengidentifikasi layanan esensial yang harus dipulihkan terlebih dahulu (prioritas pemulihan)?",
          hint_en: "Identify essential services and create a priority recovery plan based on business impact. Use the NIST CSF (Cybersecurity Framework) for risk management.",
          hint_id: "Identifikasi layanan esensial dan buat rencana pemulihan prioritas berdasarkan dampak bisnis. Gunakan kerangka kerja NIST CSF (Cybersecurity Framework) untuk manajemen risiko.",
          icon: "bi bi-hourglass",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Post-Incident Review",
      category_id: "Tinjauan Pasca Insiden",
      acronym: "PIR",
      icon: "/img/rra-icon/icon-19.png",
      detail: [
        {
          code: "B.9.1",
          question_en: "Is every incident analyzed to identify security gaps that need to be addressed?",
          question_id: "Apakah setiap insiden dianalisis untuk menemukan celah keamanan yang harus diperbaiki?",
          hint_en: "Conduct post-incident analysis to identify security gaps and areas for improvement. Use NIST SP 800-61 (Computer Security Incident Handling Guide) for incident analysis.",
          hint_id: "Lakukan analisis pasca insiden untuk mengidentifikasi celah keamanan dan area perbaikan. Gunakan metodologi NIST SP 800-61 (Computer Security Incident Handling Guide) untuk analisis insiden.",
          icon: "bi bi-file-earmark-bar-graph",
        },
        {
          code: "B.9.2",
          question_en: "Is the ransomware response plan updated based on findings from previous incidents?",
          question_id: "Apakah rencana respons ransomware diperbarui berdasarkan temuan dari insiden sebelumnya?",
          hint_en: "Update the incident response plan based on lessons learned from previous incidents. Use the PDCA (Plan-Do-Check-Act) approach for continuous improvement.",
          hint_id: "Perbarui rencana respons insiden berdasarkan pelajaran yang dipetik dari insiden sebelumnya. Gunakan pendekatan PDCA (Plan-Do-Check-Act) untuk perbaikan berkelanjutan.",
          icon: "bi bi-arrow-repeat",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Third-Party Risks",
      category_id: "Risiko Pihak Ketiga",
      acronym: "TPR",
      icon: "/img/rra-icon/icon-20.png",
      detail: [
        {
          code: "B.10.1",
          question_en: "Do vendors and partners have adequate ransomware protection measures?",
          question_id: "Apakah vendor dan mitra memiliki langkah perlindungan ransomware yang memadai?",
          hint_en: "Conduct risk assessments on vendors and partners to ensure they have adequate protection measures. Use NIST SP 800-161 (Supply Chain Risk Management Practices).",
          hint_id: "Lakukan penilaian risiko terhadap vendor dan mitra untuk memastikan mereka memiliki langkah perlindungan yang memadai. Gunakan standar NIST SP 800-161 (Supply Chain Risk Management Practices).",
          icon: "bi bi-person-raised-hand",
        },
        {
          code: "B.10.2",
          question_en: "Are there contracts ensuring vendors report security incidents that may affect the organization?",
          question_id: "Apakah ada kontrak yang memastikan vendor melaporkan insiden keamanan yang dapat memengaruhi organisasi?",
          hint_en: "Ensure contracts with vendors include clauses for security incident reporting. Use ISO 27036 (Guidelines for Cybersecurity in Supplier Relationships) for third-party risk management.",
          hint_id: "Pastikan kontrak dengan vendor mencakup klausul pelaporan insiden keamanan. Gunakan panduan ISO 27036 (Guidelines for Cybersecurity in Supplier Relationships) untuk manajemen risiko pihak ketiga.",
          icon: "bi bi-file-earmark-lock",
        },
      ],
      overallScore: 60,
    },
    {
      category_en: "Evaluate Ransom Demands",
      category_id: "Mengevaluasi Tuntutan Tebusan",
      acronym: "ERD",
      icon: "/img/rra-icon/icon-21.png",
      detail: [
        {
          code: "B.11.1",
          question_en: "Is there a policy to assess the validity of the attacker's demands, such as 'proof of life' for encrypted or stolen data?",
          question_id: "Apakah ada kebijakan untuk menilai validitas tuntutan pelaku, seperti 'proof of life' data yang dienkripsi atau dicuri?",
          hint_en: "Create a policy to verify the attacker's demands, including requesting 'proof of life' for data. Use guidance from CISA (Cybersecurity and Infrastructure Security Agency) or the FBI for evaluating demands.",
          hint_id: "Buat kebijakan untuk memverifikasi tuntutan pelaku, termasuk meminta 'proof of life' data. Gunakan panduan dari CISA (Cybersecurity and Infrastructure Security Agency) atau FBI untuk evaluasi tuntutan.",
          icon: "bi bi-search",
        },
      ],
      overallScore: 30,
    },
    {
      category_en: "Tracking Adversary Behavior",
      category_id: "Melacak Perilaku Penyerang",
      acronym: "TAB",
      icon: "/img/rra-icon/icon-22.png",
      detail: [
        {
          code: "B.12.1",
          question_en: "Is there a process to track the attacker's tactics, such as modus operandi or communication patterns?",
          question_id: "Apakah ada proses untuk melacak taktik pelaku, seperti modus operandi atau pola komunikasi?",
          hint_en: "Use the MITRE ATT&CK framework to track and analyze attacker tactics. This can help identify attack patterns.",
          hint_id: "Gunakan kerangka kerja MITRE ATT&CK untuk melacak dan menganalisis taktik pelaku. Ini dapat membantu dalam mengidentifikasi pola serangan.",
          icon: "bi bi-binoculars",
        },
      ],
      overallScore: 30,
    },
    {
      category_en: "Leverage Negotiation Tools",
      category_id: "Memanfaatkan Alat Negosiasi",
      acronym: "LNT",
      icon: "/img/rra-icon/icon-23.png",
      detail: [
        {
          code: "B.13.1",
          question_en: "Does the organization have external tools or services to assist with analysis or negotiation processes?",
          question_id: "Apakah organisasi memiliki alat atau layanan eksternal untuk membantu analisis atau proses negosiasi?",
          hint_en: "Consider using ransomware consultants or specialized analysis tools to assist with negotiations. Ensure these tools align with industry standards.",
          hint_id: "Pertimbangkan menggunakan layanan konsultan ransomware atau alat analisis khusus untuk membantu proses negosiasi. Pastikan alat ini sesuai dengan standar industri.",
          icon: "bi bi-gear-fill",
        },
      ],
      overallScore: 30,
    },
    {
      category_en: "Legal and Ethical Considerations",
      category_id: "Pertimbangan Hukum dan Etika",
      acronym: "LEC",
      icon: "/img/rra-icon/icon-24.png",
      detail: [
        {
          code: "B.14.1",
          question_en: "Do negotiation decisions comply with regulations regarding payments to sanctioned entities (e.g., OFAC or PPATK lists)?",
          question_id: "Apakah keputusan negosiasi mematuhi regulasi terkait pembayaran kepada pihak yang disanksi (misalnya, daftar OFAC atau PPATK)?",
          hint_en: "Ensure negotiation decisions comply with regulations like OFAC (Office of Foreign Assets Control) or PPATK (Indonesian Financial Transaction Reports and Analysis Center). Consult with the legal team before making decisions.",
          hint_id: "Pastikan keputusan negosiasi mematuhi regulasi seperti OFAC (Office of Foreign Assets Control) atau PPATK (Pusat Pelaporan dan Analisis Transaksi Keuangan) di Indonesia. Konsultasikan dengan tim legal sebelum mengambil keputusan.",
          icon: "bi bi-shield-exclamation",
        },
      ],
      overallScore: 30,
    },
  ],
};